### PR TITLE
Improve 2

### LINKED ISSUE #35: Syntactic highlighting not working
I can't get syntactic highlighting to work.  I don't have any extensions other than ccls installed and I have this very simple settings file:
```
{
    "ccls.highlighting.bold.macros": true,
    "ccls.highlighting.bold.freeStandingVariables": true,
    "ccls.highlighting.bold.freeStandingFunctions": true
}
```

Is there something else I need to add?

### PR DESCRIPTION
**Pull request by Yanpas**
Fixes #35 an other issues as well

### CODE REVIEW

**Comment by Yanpas** [comment]
Concerning colors removal users are used to default theme with it's colors. I'm not sure if they will see this once:
image

When there are too much colors it's hard to get their meaning

**Comment by Yanpas** [comment]
@Will-GXZ fixes #29 too

**Comment by Yanpas** [comment]
The reasons are in second comment, vscode does it better. I think defaults for bold, italics and underlined should be revised too.

Coloring each existant semantic entity is meaningless. Purpose of syntax highlight is to show keywords and some parts to pay attention to. E.g. I think underlining global variables and coloring pass by nonconst reference makes a lot of sense.

**Comment by Yanpas** [comment]
Anyway some poll would be fair. 

@Will-GXZ @Riatre what do you think?

**Comment by Yanpas** [comment]
@MaskRay 
Oh, nevermind, I didn't notice that there is 'enabled' setting which is off by default. Will revert my changes. I was enabling semantic if one of bold, italic and underline are true.

**Comment by MaskRay** [comment]
Manually cherry-micked..

**Comment by Will-GXZ** [comment]
> Anyway some poll would be fair.
> 
> @Will-GXZ @Riatre what do you think?

To be honest, when I use ccls during work, I only use vscode default highlight. I tried turn on highlights setting before, but for me there were too many colors on the screen and they were kind of distracting.

>  I think underlining global variables and coloring pass by nonconst reference makes a lot of sense 

-- I vote to this.

**Pull request closed without merging**
