### PR TITLE
Add support for semantic navigation

### PR DESCRIPTION
**Pull request by icylogic**
semantic-navigation

Implementing semantic navigation.

### CODE REVIEW

**Comment by icylogic** [comment]
Note: You could set your own key bindings to these commands:
```json
        "command": "ccls.navigateFirstChild"
        "command": "ccls.navigateParent"
        "command": "ccls.navigatePrevious"
        "command": "ccls.navigateNext"
```
If you are using VSCodeVim like I do, consider mapping keys in `settings.json`:
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "j"],
            "commands": ["ccls.navigateNext"]
        },
        {
            "before": ["<leader>", "k"],
            "commands": ["ccls.navigatePrevious"]
        },
        {
            "before": ["<leader>", "h"],
            "commands": ["ccls.navigateParent"]
        },
        {
            "before": ["<leader>", "l"],
            "commands": ["ccls.navigateFirstChild"]
        }
    ]
```

**Comment by MaskRay** [comment]
I introduced `$ccls/navigate` before https://github.com/MaskRay/ccls/releases/tag/0.20180913 and put the generic `ccls-navigate` (but not the 4 variants) into emacs-ccls (https://github.com/MaskRay/ccls/wiki/Emacs#ccls-navigate) because Emacs users tend to have different customization needs. It is also easy to bind keys in Vim/Neovim with LanguageClient-neovim (https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim#cclsnavigate).

I understand that VSCode users may be more accustomed to predefined commands in a menu...

Is it easy to send other custom requests in VSCode? @Riatre

**Comment by icylogic** [comment]
OK, I'll fix it next week. I need to add some documentation so users know how to use it.

@Riatre 
You can let user quickly pick an option from a list or input some text after your command is invoked. Just like what GitLens do when `Show File History` is called.

**Comment by icylogic** [comment]
closed in favor of #8

**Pull request closed without merging**
