### PR TITLE
Add option to show detailed name of entry in call hiearchy

### PR DESCRIPTION
**Pull request by withgod84**
Reason:
It's very confused that which class's method calls symbol if many classes
have same or similar name of method.

Configuration:
ccls.detailedLable: true by default
If true, detailed name is used to each entry in call hiearchy, instead of symbol name

### CODE REVIEW

**Comment by MaskRay** [comment]
Should the option be named `ccls.callHierarchy.qualified`? The initialization option `completion.detailedLabel` (see `ccls/src/config.hh`) means a different thing.

**Comment by withgod84** [comment]
> Should the option be named `ccls.callHierarchy.qualified`? The initialization option `completion.detailedLabel` (see `ccls/src/config.hh`) means a different thing.

Thanks for comment, 
I'll create new pull request. 

Anyway, I'll really appreciate your excellent plugin and ccls!
This helps a lot of my work with big-sized project

Best regards,
Deok Koo

**Comment by withgod84** [comment]
Now, it's ready to merge in my opinion.

**Comment by MaskRay** [comment]
Sorry for my late response. Merged with some tweaks.

**Pull request closed without merging**
